<a href="https://colab.research.google.com/github/tugcenurozkan/Colab_Working/blob/main/veribilimideneme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HAZIR FONKSİYONLAR**


In [ ]:
selam="hello"


In [ ]:
selam

'hello'

In [ ]:
selam.upper()


'HELLO'

In [ ]:
selam.isupper()

False

In [ ]:
a=selam.upper()
a

'HELLO'

In [ ]:
a.isupper()

True

In [ ]:
selam.replace("e","")

'hllo'

In [ ]:
selam

'hello'

In [ ]:
selam.replace("e","a")

'hallo'

In [ ]:
selam.capitalize()

'Hello'

In [ ]:
?print

In [ ]:
degisken=4

In [ ]:
degisken*degisken

16

# **VERİ YAPILARI**

# **GENEL ÖZELLİKLERİ**

![My Image](https://github.com/tugcenurozkan/colabPhoto/blob/main/DataStructure.jpeg?raw=true)



# **LİSTELER []**


>Listeler farklı türde yapılar barındırır/sıralıdır yani indexlenir/değiştirilebilir.





In [ ]:
sayilar = [10,20,30,40]
 
for i in sayilar:
    if i == 30:
        break
    print(i)

10
20


In [ ]:
if [0,1,2][2]==2:
  print("yes")
else:
  print("no")

yes


In [ ]:
notlar=[90,50,"ali"]

In [ ]:
for x in notlar:
  print(x)



90
50
ali


In [ ]:
liste=[50,45,"a",notlar]


In [ ]:
liste

[50, 45, 'a', [90, 50, 'ali']]

In [ ]:
for x in liste:
  print(x)


50
45
a
[90, 50, 'ali']


In [ ]:
len(liste[2])

1

In [ ]:
type(liste[1])

int

In [ ]:
liste[3][2]

'ali'

In [ ]:
liste

[50, 45, 'a', [90, 50, 'ali']]

In [ ]:
liste+["kemal"]
#burda kemal listeye eklenir ama kalıcı değildir.atama olmadığı için 

[50, 45, 'a', [90, 50, 'ali'], 'kemal']

In [ ]:
liste


[50, 45, 'a', [90, 50, 'ali']]

In [ ]:
liste=liste+["kemal"]

In [ ]:
liste
#burda artık üst satırdaki atama sayesinde kalıcı olarak eklendiği görülmekte.

[50, 45, 'a', [90, 50, 'ali'], 'kemal']

In [ ]:
liste.append("veli") 
#aynı ekleme şeklini append metodu ile yapmak mümkün

In [ ]:
liste

[50, 45, 'a', [90, 50, 'ali'], 'kemal', 'veli']

In [ ]:
del liste[1]
#listeden herhangi bir eleman silme

In [ ]:
liste

[50, 'a', [90, 50, 'ali'], 'kemal', 'veli']

In [ ]:
liste.remove("a")
#listeden metodla eleman silme

In [ ]:
liste

[50, [90, 50, 'ali'], 'kemal', 'veli']

In [ ]:
dir(liste)
#burda listenin alabileceği fonksiyonları görebilmekteyiz.

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
liste.insert(0,"hello")
#burda istenen index e eleman atama var bunu yapınca diğer elemanların indexi bir kayar liste[0]="hello" deseydik direk ilk eleman değişirdi.

In [ ]:
liste

['hello', 50, [90, 50, 'ali'], 'kemal', 'veli']

In [ ]:
liste.insert(len(liste),"selam")
#sona ekledik.

In [ ]:
liste

['hello', 50, [90, 50, 'ali'], 'kemal', 'veli', 'selam']

In [ ]:
liste.pop(1)
#indexleme ile eleman silindi.

50

In [ ]:
liste

['hello', [90, 50, 'ali'], 'kemal', 'veli', 'selam']

In [ ]:
liste.count("hello")
#listede kaç tane içine yazılan değer var onu gösteriyor.

1

In [ ]:
liste_yedek=liste.copy()
#listeyi kopyalama

In [ ]:
liste_yedek

['hello', [90, 50, 'ali'], 'kemal', 'veli', 'selam']

In [ ]:
liste.extend([50,60,20])
#listeleri birleştirme

In [ ]:
liste

['hello', [90, 50, 'ali'], 'kemal', 'veli', 'selam', 50, 60, 20]

In [ ]:
liste.index("kemal")
#kemal in hangi index de olduğunu bulur

2

In [ ]:
liste.reverse()
#listeyi ters çevirme

In [ ]:
liste

[20, 60, 50, 'selam', 'veli', 'kemal', [90, 50, 'ali'], 'hello']

In [ ]:
yeniliste=[50,79,20,10,45,78,6]

In [ ]:
yeniliste.sort()
#sıralama

In [ ]:
yeniliste

[6, 10, 20, 45, 50, 78, 79]

# **TUPLE(DEMET) LAR ()** 

> İçerisinde farklı türden yapılar barındırabilir/sıralıdır/içerisi **değiştirilemez**



In [ ]:
tup=("ali","veli",2,4,5.6)
#parantez ile oluşturulur.

In [ ]:
type(tup)

tuple

In [ ]:
tup2="ali","veli",2,4,5.6  
#->> parantezsiz de direk bu şekilde oluşturulabilir.

In [ ]:
type(tup2)

tuple

In [ ]:
len(tup2)

5

In [ ]:
tup3=("eleman")

In [ ]:
type(tup3)
#burda tuple oluşturduğumuz halde str döndürdü bi istisna denebilir bilgisayarın bunu tuple olarak algılayabilmesi için aşağıdaki kod uygulanmalı

str

In [ ]:
tup3=("eleman",)
#burda elemandan sonra virgül konulursa bunu tuple olarak algılar.

In [ ]:
type(tup3)

tuple

In [ ]:
dir(tuple)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [ ]:
tup

('ali', 'veli', 2, 4, 5.6)

In [ ]:
tup[1]

'veli'

In [ ]:
tup[0:2]
#0 dan başlar sonuncusunu dahil etmeden içindekileri ekrana basar

('ali', 'veli')

In [ ]:
tup[1]="ali"
#burda değiştirilemediği için hata verir.Atama yapılamayacağını görmüş olduk.

TypeError: ignored

# **DICTIONARY(SÖZLÜK) {}**

>Birden fazla yapı türü barındırırır./**Sırasızdır->yani listedeki gibi indexleme yapılamaz**/Değiştirilebilir.

>**key:value** çiftleri vardır





In [ ]:
sozluk={"hello":"world",
        "loj":"lojistik regresyon",
        "cart":"sınıflandırma"}

In [ ]:
sozluk

{'cart': 'sınıflandırma', 'hello': 'world', 'loj': 'lojistik regresyon'}

In [ ]:
len(sozluk)

3

In [ ]:
sozluk={"hello":10,
        "loj":20,
        "cart":30}
        #değiştirilebilir olduğunu gördük.

In [ ]:
sozluk

{'cart': 30, 'hello': 10, 'loj': 20}

In [ ]:
sozluk={"hello":["devam",10],
        "loj":20,
        "cart":30}
        #burda da liste ataması yapabildik dictionary içinde.

In [ ]:
sozluk

{'cart': 30, 'hello': ['devam', 10], 'loj': 20}

In [ ]:
sozluk["cart"]
#burda içine [2] yazamazdık cart gelmesi için çünkü indexleme yapılamıyordu.

30

In [ ]:
sozluk={"hello":["devam",10],
        "loj":20,
        "cart":30}
        #burda da liste ataması yapabildik dictionary içinde.

In [ ]:
sozluk['hello']

['devam', 10]

In [ ]:
sozluk={"hello":{"devam":10,
                 "tekrar":20,
                 "sozluk":30},
        "loj":20,
        "cart":30}
        #burda sozluk içine sozluk yazabiliriz.

In [ ]:
sozluk["hello"]

{'devam': 10, 'sozluk': 30, 'tekrar': 20}

In [ ]:
sozluk["hello"]["devam"]
#sözlük içinde sözlük olduğunda bu şekilde en içtekine erişebilmek mümkün key değerlerini yazarak 

10

In [ ]:
sozluk["eklemeyedevam"]="ekliyoruz"
#dictionary eleman ekleme

In [ ]:
sozluk

{'cart': 30,
 'eklemeyedevam': 'ekliyoruz',
 'hello': {'devam': 10, 'sozluk': 30, 'tekrar': 20},
 'loj': 20}

In [ ]:
sozluk["loj"]=60
#içindeki key değerinin value sunu değiştirmek için

**Dictionary içinde eğer yeni bir key değeri yazarsak program bunun olmadığını görüp ekleme yapar ancak içinde olan bir key değeri yazarak atama yaparsak o zman içindekini değiştirir.**

In [ ]:
sozluk

{'cart': 30,
 'eklemeyedevam': 'ekliyoruz',
 'hello': {'devam': 10, 'sozluk': 30, 'tekrar': 20},
 'loj': 60}

In [ ]:
sozluk[6]="yapay sinir ağları"

In [ ]:
sozluk

{6: 'yapay sinir ağları',
 'cart': 30,
 'eklemeyedevam': 'ekliyoruz',
 'hello': {'devam': 10, 'sozluk': 30, 'tekrar': 20},
 'loj': 60}

In [ ]:
sozluk[1]
#burda hata verir key değeri içerisinde olmadığı için.

KeyError: ignored

In [ ]:
l=[1]
l

[1]

In [ ]:
sozluk[l]="hello"
#burda hata verme sebebi dictionary yapısı key değeri olarak sabit veri yapıları ifadeleri alır(string , int , tuple). Listeyi key değeri olarak veremezsin. Key sabir bir referans değeri olduğu için

TypeError: ignored

In [ ]:
t=("tupleelemanı",)
t

('tupleelemanı',)

In [ ]:
sozluk[t]="tuple dictionaryb yapısında key olarak kullanılabildi."

In [ ]:
sozluk

{('tupleelemanı',): 'tuple dictionaryb yapısında key olarak kullanılabildi.',
 6: 'yapay sinir ağları',
 'cart': 30,
 'eklemeyedevam': 'ekliyoruz',
 'hello': {'devam': 10, 'sozluk': 30, 'tekrar': 20},
 'loj': 60}

# **SET(KÜMELER) LER set()**

> **Sırasızdır(Indexleme yapılamaz)/ Değerleri eşssizdir(Unique)**/Değiştirilebilir./Farklı tipleri içerisinde barındırır.

> İçerisinde Unique istendiğinde ve hız istendiğinde kullanılır





In [ ]:
s=set()

In [ ]:
type(s)

set

In [ ]:
liste=[1,2,6,45,7]

In [ ]:
s=set(liste)
s
#burda set içerisinde liste oluşturabiliriz.

{1, 2, 6, 7, 45}

In [ ]:
tuple2=("sdf","sdf",12)

In [ ]:
s=set(tuple2)
s
#tuple ile set oluşturuldu ve görüldüğü gibi iki tane aynı değerden olduğu için onu tek aldı.

{12, 'sdf'}

In [ ]:
deneme="bugün seni çarşıda=musmutlu*gördüm"

In [ ]:
s=set(deneme)
s
#unique değerler aldığı için her harf bi kere yazılıyor ve string i karakterlere parçalayarak aldı.boşluk = hepsini bir karakter olarak alır.

{' ',
 '*',
 '=',
 'a',
 'b',
 'd',
 'e',
 'g',
 'i',
 'l',
 'm',
 'n',
 'r',
 's',
 't',
 'u',
 'ç',
 'ö',
 'ü',
 'ı',
 'ş'}

In [ ]:
len(s)

21

In [ ]:
l=["geleceği","yazanlar"]
s=set(l)
s

{'geleceği', 'yazanlar'}

In [ ]:
dir(s)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
s.add("ile")
s
#sona eklenmesi beklenir ama sırasız olduğu için öyle olmuyor.

{'geleceği', 'ile', 'yazanlar'}

In [ ]:
s.add("ile")
s
#hata vermeden ekledi ama unique olduğu için yine tek ile oldu 

{'geleceği', 'ile', 'yazanlar'}

In [ ]:
s.remove("ile")
s

{'geleceği', 'yazanlar'}

In [ ]:
s.remove("ile")
s
#hata verdi çünkü ile set içerisinde yok ama eğer silmesin ama hata da vermesin istersek 

KeyError: ignored

In [ ]:
s.discard("ile")
s
#burda içerisinde "ile" olmamasına rağmen hata vermedi. Kod akışı bozulmadı.

**KLASİK KÜME İŞLEMLERİ**

> difference() ->> ile iki kümenin farkını ya da "-" ifadesi

> intersection() ->> iki küme kesişimi ya da "&" ifadesi

> union() ->> iki kümenin birleşimi

> symmetric_difference() ->> ikisinde de olmayanları




In [ ]:
set1=set([1,3,5])
set2=set([1,2,3])

In [ ]:
set1.difference(set2)
#set1 de olup set2 de olmayan

In [ ]:
set1-set2
#bu işlem yukarda belirtildiği gibi "-" ifadesiyle de sağlanmış olur
#tabiki "-" işlemi yapmak toplama çarpma gibi işlemlerin yapıldığı anlamına gelmez.

In [ ]:
set1.symmetric_difference(set2)
#hem set1 de hem set2 de aynı anda bulunmayanları temsil eder.

In [ ]:
set1.intersection(set2)
#kesişim işlemi hem böyle hem de aşağıdaki "&" ifadesi ile sağlanmaktadır.

In [ ]:
set1 & set2

In [ ]:
set1.union(set2)
#unique olarak birleşmiş oldu.

In [ ]:
set1.intersection_update(set2)
#ile set1 ve set2 nin kesişimini set1 in kalıcı elemanları olmasını sağlamak için kullanılır.

In [ ]:
set1

**SET SORGU İŞLEMLERİ**

In [ ]:
set1=set([7,8,9])
set2=set([5,6,7,8,9,10])

In [ ]:
#iki kümenin kesişiminin boş olup olmadığını sorgulaması.
set1.isdisjoint(set2)
#false döndü demek ki boş değilmiş

In [ ]:
#bir kümenin bütün elemanlarının başka bir küme içerisinde yer alıp almadığını sorgulama yani alt küme 
set1.issubset(set2)
#set1 set2 n,n alt kümesi midir? öyleyse true döner

In [ ]:
#bir kümenin diğer kümeyi kapsayıp kapsamaması. aslında yukardaki kodun tam tersi
set2.issuperset(set1)
#set2 set1 i kapsıyor mu

# **FONKSİYONLAR**

> **def** anahtar sözcüğü ile fonksiyonlar tanımlanır.



In [ ]:
print
#fonksiyon olduğu çıktıda görülmekte.

<function print>

In [ ]:
?print
#yan sekmede print ifadesinin aldığı değerler argümanlar açıklanmakta

In [ ]:
print("a","b",sep="_", end="g")
#"end" ile sona ekleme yapıldığı argüman içerisinde açıklanmakta "sep" ile ise iki değer birleşimini neyle bağlamak istediğini ifade edersin.

a_bg

In [ ]:
def kare_al(x):
  print(x**2)
#kare alma işlemi fonksiyon ile 
#burda ekrana yazmasını istediğimiz için print ifadesini kullandık ancak ekrana yazdırmaktan ziyade.. 
#..bir değer döndürüp o değer üzerinde işlem yapmak istersek return kullanırız.

In [ ]:
type(kare_al)

function

In [ ]:
kare_al(5)

25


In [ ]:
def kare_al(x):
  print("Girilen sayının karesi:"+ str(x**2))
#burda "+" yerine "," koyarsan sorun çıkmaz ancak + konulduğunda sadece str type lar birbirine bağlanabilir hatası verir.
#böyle bir durunda x**2 yi str ile cover lalrsak sorun çözülmüş olur. 

In [ ]:
kare_al(6)

Girilen sayının karesi:36


In [ ]:
def carpma(x, y):
  print(x*y)

In [ ]:
carpma(5,9)

45


**ÖN TANIMLI ARGÜMANLAR**

> Burda sep ,end gibi argümanların ön tanımı ?print yazdığımızda gösterilen ilk değerleridir. Mesela sep için boşluk end için alt satıra geçmek olarak ifade edilmiştir.



In [ ]:
carpma(5)
#burda hata almamızın sebebi parametre eksik yazılmasından kaynaklıdır.
#Ancak aşapıdaki kodda yazıldığı gibi ön tanımlı argüman olarak y tanımlanırsa hat vermeyecektir.

TypeError: ignored

In [ ]:
def carpma(x, y=1):
  print(x*y)
#görüldüğü gibi ön tanımlama yaptığımızda çağrılan fonksiyon tek paramatre ile hata vermedi.

In [ ]:
carpma(5)

5


In [ ]:
carpma(5,6)
#burda 6 yı eklediğimizde artık yukarda yanımlanan y=1 değerini göz ardı eder

30


In [ ]:
carpma(y=5,x=6)
#burda sıra arz etmeksizin sıralamasını bilmediğimiz bir fonksiyon kullanıyorsak x ve y için adlarını kullanarak 
#atama yapıp da sırasız olarak çalıştırmak mümkün


30


**Çıktıyı girdi olarak kullanmak**

In [ ]:
output=carpma(2,5)

10


In [ ]:
print(output)
#burda görüldüğü üzere carpma ile oluşturulan çıktının değerini atam ayaptığımızda elde edemedik.
#bunu yapabilmek için print fonksiyonu yerine return kullanmamız gerekiyor.

None


In [ ]:
def carpma(x, y=1):
  return (x*y)

In [ ]:
output=carpma(2,5)

In [ ]:
output
#return döndürdüğümüz için fonksiyon çıktımızı girdi olarak kullanabilir hale getirdik.

10

In [ ]:
def carpma(x, y=1):
  return 
  (x*y)

In [ ]:
carpma(2,5)
#burda çalıştırınca bir çıktı vermez çünkü yukarda fonksiyonda return ifadesi görünce durur ve alt satırı görmez.
#bu yüzden return yanına yazılmalı döndürülmek istenen değer

**Local ve Global Değişkenler**

> Global Değişkenler: sabittir değişmezler.


> Local Değişkenler: Fonksiyon içindeki geçici değişkenlerdir. Burdaki değerleri globaldeki değerleri etkilemez.





**Local Etki Alanından Global Etki Alanını Değiştirmek**

In [ ]:
x=[]
def eleman_ekle(y):
  x.append(y)
  print(str(y)+" ifadesi eklendi")

#python aslında fonksiyon çalışınca localde arama yapar yani kendi içerisinde arama yapar.
#baktı ki x fonksiyon içerisinde yok o zaman globalde değişime gider.

In [ ]:
  eleman_ekle(57)

57 ifadesi eklendi


In [ ]:
  eleman_ekle("ali")

ali ifadesi eklendi


In [ ]:
x

[57, 'ali']

# **KARAR KONTROL YAPILARI**

In [ ]:
#True false sorguları
x=5 
x==4

False

In [ ]:
x==5

True

**IF-ELSE-ELIF**

In [ ]:
sinir=500
gelir=400

In [ ]:
if gelir<sinir:
  print("gelir sınırdan küçük")
#true dönerse print ifadesini basar

gelir sınırdan küçük


In [ ]:
gelir=600

In [ ]:
if gelir<sinir:
  print("gelir sınırdan küçük")
#true dönerse print ifadesini basar değilse else dekini basar

else:
  print("gelir sınırdan büyük")

gelir sınırdan büyük


In [ ]:
if gelir<sinir:
  print("gelir sınırdan küçük")
#true dönerse print ifadesini basar değilse else dekini basar
elif gelir>sinir:
  print("gelir sınırdan büyük")
#birden fazla koşul varsa elif kullanılır ve bu koşullar dışında kalanları ise else kapsar.
else:
  print("gelir sınıra eşit")

gelir sınırdan büyük


In [ ]:
gelir=500

In [ ]:
if gelir<sinir:
  print("gelir sınırdan küçük")
#true dönerse print ifadesini basar değilse else dekini basar
elif gelir>sinir:
  print("gelir sınırdan büyük")
#birden fazla koşul varsa elif kullanılır ve bu koşullar dışında kalanları ise else kapsar.
else:
  print("gelir sınıra eşit")

gelir sınıra eşit


In [ ]:
#mini uygulama

sinir=500
magaza_adi=input("mağaza adı: ")
gelir=int(input("gelir: "))

if gelir<sinir:
  print("magaza adi: "+ magaza_adi + " -gelir: "+ str(gelir) + " -gelir sınırdan küçük")
#true dönerse print ifadesini basar değilse else dekini basar
elif gelir>sinir:
  print("gelir sınırdan büyük")
#birden fazla koşul varsa elif kullanılır ve bu koşullar dışında kalanları ise else kapsar.
else:
  print("gelir sınıra eşit")


mağaza adı: A
gelir: 300
magaza adi: A -gelir: 300 -gelir sınırdan küçük


# **DÖNGÜLER**

In [ ]:
ogrenci=["ali","veli","karaca"]

In [ ]:
for i in ogrenci:
  print(i + " hello")

ali hello
veli hello
karaca hello


In [ ]:
maaslar=[100,20,165,12]

In [ ]:
#burda maaslar listesi içinde maasşlara %20 zam yapılmış yeni hallerini görmek istersek for döngüsü ve fonksiyon ile haleldebiliriz.
def yeni_maas(x):
  print(x*20/100+x)

for i in maaslar:
  yeni_maas(i)

120.0
24.0
198.0
14.4


In [ ]:
#mini uygulama
#3000 den yukarısına %10 
#3000 den azına %20 zam

maaslar=[1000,2000,3000,4000,5000,6000]

def maas_yuksek(x):
  print(x*10/100+x)

def maas_dusuk(x):
  print(x*20/100+x)

for i in maaslar:
  if i<=3000:
    maas_dusuk(i)
  else:
    maas_yuksek(i)

1200.0
2400.0
3600.0
4400.0
5500.0
6600.0


In [ ]:
#break/continue
#3000 altına kadar devam et 3000 i görünce dur 
maaslar=[8000,5000,2000,1000,3000,7000,1000]
maaslar.sort()

for i in maaslar:
  if i==3000:
    print("kesildi")
    break
  print(i)

#break istenen işleme gelince döngüyü sonlandırır.

1000
1000
2000
kesildi


In [ ]:
maaslar=[8000,5000,2000,1000,3000,7000,1000]
maaslar.sort()

for i in maaslar:
  if i==3000:
    continue
  print(i)
#3000 e gelince döngüye geri döndü ve ekrana yazdırmadı!!!

1000
1000
2000
5000
7000
8000


In [ ]:
#while ->> bu şart sağlandığı sürece devam
sayi=1
while sayi<10:
  print(sayi)
  sayi+=1

1
2
3
4
5
6
7
8
9


In [ ]:
def yazdir(metin):
    print(metin, "yazanlar")
 
yazdir("gelecegi")

gelecegi yazanlar


# **NESNE YÖNELİMLİ PROGRAMLAMA**

> Sınıf: benzer özellikler, ortak amaçlar taşıyan, içerisinde metod ve değişkenler olan yapılardır.


In [ ]:
class VeriBilimci():
  print("bu bir class tır")

bu bir class tır


In [ ]:
class VeriBilimci():
  bolum=''
  sql='Evet'
  deneyim_yılı=0
  bildiği_diller=[]
  

In [ ]:
VeriBilimci.sql
#sınıfların özelliklerine erişmek

'Evet'

In [ ]:
VeriBilimci.sql="No"
#class elemanlarını dışardan kalıcı değiştirebilirsin.

In [ ]:
VeriBilimci.sql

'No'

In [ ]:
#sınıf örneklendirmesi(instantiation)
ali=VeriBilimci()

In [ ]:
ali.sql

'No'

In [ ]:
ali.deneyim_yılı

0

In [ ]:
ali.bildiği_diller.append("python")
#burada yapılan değişiklik sınıfın özelliklerini etkiler 

In [ ]:
ali.bildiği_diller

['python']

In [ ]:
veli=VeriBilimci()

In [ ]:
veli.sql

'No'

In [ ]:
veli.bildiği_diller
#veli de python tanımlanmamasına rağmen python ali de tanımlandığı için çıktı çünkü sınıfı etkiledi

['python']

In [ ]:
#Peki bu class da değişme sorununu nasıl düzeltebiliriz?
class VeriBilimci():
  def __init__(self):    #burda init kısmı tamamen nesneler üzerinde oluşacak değişimler için tanımlanmaktadır.
    self.bildigi_diller=[]

#aşağıdaki örneklerde görüldüğü üzere artık nesneler üzerinden değişim yapıldığında class bazında bir değişim meydana gelmemekte ve bilgi diller veli için bos dönmenktedir ali değişsse bile 

In [ ]:
ali=VeriBilimci()
ali.bildigi_diller

[]

In [ ]:
veli=VeriBilimci()
veli.bildigi_diller

[]

In [ ]:
ali.bildigi_diller.append("python")

In [ ]:
ali.bildigi_diller

['python']

In [ ]:
veli.bildigi_diller

[]

In [ ]:
veli.bildigi_diller.append("R")

In [ ]:
VeriBilimci.bildigi_diller
#burda attribute hatası alırız çünkü bizim yukarda init ile yaptığımız özellik nesneler üzerindeki değişimler içinde 

AttributeError: ignored

In [ ]:
#yukarıdaki hatayı düzeltmek için VeriBilimci sınıfına da istenen özellik eklenmeli
class VeriBilimci():
  bolum=''
  sql='Evet'
  deneyim_yılı=0
  bildigi_diller=["R","Python"]
  def __init__(self):    #burda init kısmı tamamen nesneler üzerinde oluşacak değişimler için tanımlanmaktadır. Bu sayede nesnelerdeki değişim class ın genel özelliklerini değiştirmeyecek.
    self.bildigi_diller=[]
    self.bolum=""

In [ ]:
ali=VeriBilimci()

In [ ]:
VeriBilimci.bildigi_diller

['R', 'Python']

In [ ]:
ali.bildigi_diller
#görüldüğü üzeri yeni oluşturulan nesle ile class ın genel özelliğinde var olan bildigi_diller özelliği arasında bir bağlantı kalmadı.

[]

In [ ]:
ali.bildigi_diller.append("Python")

In [ ]:
ali.bildigi_diller
#aynı şekilde burda eklenen ile genel class daki bilinen diller arasında bir bağ kalmadığı görülmekte

['Python']

In [ ]:
ali.bolum

''

In [ ]:
ali.bolum="computer"

In [ ]:
ali.bolum

'computer'

In [ ]:
VeriBilimci.bolum
#bir üst satırda aliye ekleme yapılsa bile veribilimci sınıfındaki bolum yine birbirinden bağımsız kaldı. def __init__(self) metodu sayesinde 

''

In [ ]:
veli=VeriBilimci()
veli.bolum
#yine görüldüğü üzere alinin computer olarak eklenen bölümü veli de gözükmemekte yani aliye özel bir nitelik olarak ifade etmiş bulunduk. __init__ ile.
#self örnekleri temsil etmekte.(__init__(self))

''

**Genelde sınıfın ve örneklerin(yani nesnelerin(ali,veli)) attribute ları farklı isimlendirmekte fayda var.**

In [ ]:
#ÖRNEK METODLARI
class VeriBilimci():
  calisanlar=[]
  def __init__(self):    #burda init kısmı tamamen nesneler üzerinde oluşacak değişimler için tanımlanmaktadır. Bu sayede nesnelerdeki değişim class ın genel özelliklerini değiştirmeyecek.
    self.bildigi_diller=[]
    self.bolum=""
  def dil_ekle(self,yeni_dil):  #burda bir fonksiyon tanımladık her defasında ali örneği üzerinden appen yapmakla uğraşmamak adına daha kısa yoldan.
#self her zaman olmalı çünkü bu oluşturulan nesneyi temsil eder.Self burda örnekler üzerinde çalışma sağlar.
    self.bildigi_diller.append(yeni_dil)

In [ ]:
ali =VeriBilimci()
veli=VeriBilimci()

In [ ]:
ali.bolum

''

In [ ]:
dir(VeriBilimci)
#sınıflarda bir nesnedir ve sınıfın kullanılabilecek olan değeri gözükmekte ve görüldüğü gibi bizim eklediğimiz calisanlar ve yeni_dil kısmı gözükmekte.

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'calisanlar',
 'dil_ekle']

In [ ]:
VeriBilimci.dil_ekle

<function __main__.VeriBilimci.dil_ekle>

In [ ]:
VeriBilimci.dil_ekle("R")
#burdaki hata sebebi şudur ki sınıf içerisinde böyle bir tanımlama yapılmamıştır.BUu özellik oluşturulan nesne üzerinden ulaşmak için yapılmıştır ve self kullanılmıştır.

TypeError: ignored

In [ ]:
ali.dil_ekle("R")

In [ ]:
ali.bildigi_diller

['R']

In [ ]:
ali.bolum

''

**MİRAS YAPILARI(INHERITANCE)**

Kendi __init__ metodumuzu yazdığımızda, miras alınan sınıfın __init__ metodu geçersiz kaldığı için çağırılmıyor. Biz eğer çağırılmasını istiyorsak super().__init__() gibi bir yapı kullanıyoruz.

In [ ]:
class Employees():
  def __init__(self):
    self.FirstName=""
    self.LastName=""
    self.Address=""

class DataScience(Employees):
  def __init__(self):
    super().__init__()
    self.Programming=""
    

class Marketing(Employees):
  def __init__(self):
    self.StoryTelling=""


In [ ]:
science=DataScience()

In [ ]:
science.FirstName

''

In [ ]:
#daha fonksiyonel bir yapı oluşturmak istersek
class Employee_yeni():
  def __init__(self,FirstName,LastName,Address):
    self.FirstName=FirstName
    self.LastName=LastName
    self.Address=Address

In [ ]:
#ali=Employee_yeni() burda hata verir. yukarda içine parametre tanımlandığı için.
ali=Employee_yeni("a","b","c")
#sınıfı fonksiyon gibi tanımladık.Constructor aslında

In [ ]:
ali.FirstName

'a'

**İNTERNETTEN BULUNAN ARA ÖRNEKLER**

In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def introduceyourself(self):
        print("My name is " + self.name)
        print("My age is " + str(self.age))

        
class Teacher(Person): #this class inherits the class above!
    def stateprofession(self):
        print("I am a teacher!")

In [ ]:
author = Teacher("Maarten",30)
author.introduceyourself()
author.stateprofession()

My name is Maarten
My age is 30
I am a teacher!


In [ ]:
class Teacher(Person): #this class inherits the class above!
    def __init__(self, name, age):
        self.courses = [] #initialise a new variable
        super().__init__(name,age) #call the init of Person
        
    def stateprofession(self):
        print("I am a teacher!")        
    
    def introduceyourself(self):
        super().introduceyourself() #call the introduceyourself() of the Person
        self.stateprofession()
        print("I teach " + str(self.nrofcourses()) + " course(s)")
        for course in self.courses:
            print("I teach " + course)
      
        
    
    def addcourse(self, course):
        self.courses.append(course)
        
    def nrofcourses(self):
        return len(self.courses)
    
    
author = Teacher("Maarten",30)
author.addcourse("Python")
author.introduceyourself()


My name is Maarten
My age is 30
I am a teacher!
I teach 1 course(s)
I teach Python


# **PYTHON DA FONKSİYONEL PROGRAMLAMA**



> Burda yapılan işlemler tamamen fonksiyonlar üzerine kuruludur ve oop ile sağlanan dışardan değiştirme işlemleri fonksiyonel programlamada sadece fonksiyona girdi verildiği müddetçe değişebilmektedir.


> Yan etkisiz fonksiyonlar(stateless, girdi-çıktı)  PURE FUNCTION

> Yüksek seviye fonksiyonalar(Daha az çaba ile daha çok iş yapma)

> Daha esnek ve bizi daha iyi anlayan

> Vektörel operasyonlar









In [ ]:
#Bağımsızlık örneği pure_sum()

A=8
def impure_sum(b):
  return b+A 



In [ ]:
impure_sum(9)#A=5 iken 14 veriyor ancak yukarda A yyı değiştirirsek sonuç 17 olarak değişecek. burda bir bağımlılık söz konusu fonksiyon dışardan global bir 
#değişkene bağlı kaldığı için ilerleyen seviyelerde bize sorun yaratabilir.

17

In [ ]:
def pure_sum(a,b):
  return a+b

In [ ]:
pure_sum(4,7) #burda ise A istediği kadar değişsin bizim verdiğimiz girdi değişmeden çıktı değişmez. Bağımsızdır dışarıya

11

 **Ölümcül Yan Etkiler OOP**

> Burda class içinde bir fonksiyon çağrımıyla birlikte ilk başta alınan [] ve 0 değerleri read() fonksiyonu çağrımı sonrası değiştiği gözlemlenmektedir ve bu durum bazen istenmeyebilir.


In [ ]:
class LineCounter:
  def __init__(self,filename):
    self.file=open(filename,'r')
    self.lines=[]
  def read(self):
    self.lines=[line for line in self.file]
  def count(self):
    return len(self.lines)


In [ ]:
lc=LineCounter('deneme.txt')

In [ ]:
print(lc.lines)
print(lc.count())


[]
0


In [ ]:
lc.read()

In [ ]:
print(lc.lines)
print(lc.count())

['bu bir denemedir.\n', 'tekrar deneyelim umarız olur']
2


**Yukardaki örneği bir de fonksiyonel programlama ile ele alalım**

> Bu örnekte görüldüğü üzeri biz girdi vermediğimiz sürece bir çıktı değişimi söz konusu olmayacaktır.


> Tamamen birbirinden bağımsız fonksiyonlardır.




In [ ]:
def read(filename):
  with open(filename,'r') as f:
    return [line for line in f]

def count(lines):
  return len(lines)

In [ ]:
example_lines=read('deneme.txt')
lines_count=count(example_lines)

In [ ]:
lines_count

2

In [ ]:
type(example_lines)

list

**Anonymous Function (İsimsiz Fonksiyonlar)**

In [ ]:
new_sum=lambda a,b :a+b #burda a ve b parametreli ve a+b işlemi yapan fonksiyon yazıldı isimsiz olarak 
#aşağıdaki fonksiyona denktir.
#def sum(a,b):                    
#  return a+b

In [ ]:
new_sum(4,7)

11

In [ ]:
sirasiz_liste=[('b',3),('a',8),('d',12),('c',1)]
sirasiz_liste[1][1]

8

In [ ]:
sorted(sirasiz_liste,key=lambda x:x[1]) #burda da lambda kullanarak x parametreli x[1] işlemi yapan bir isimsiz fonksiyon 
#tanımlaması yapmış olduk.
#burda aslında x olarak girilne girdi ( , ) tuple lardır be bunların 1. elemanına göre sırala dendiğinde virgülden sonrası alınır.

[('c', 1), ('b', 3), ('a', 8), ('d', 12)]

**Vectorel Operations(Vektörel Operasyonlar)**

**OOP**

In [ ]:
a=[1,2,3,4]  #tek boyut olduğundan vektör denir.
b=[2,3,4,5]
ab=[] #çarpma işleminin değerlerinin saklanması için

In [ ]:
for i in range(0,len(a)):
  print(i)#bu sefer içinde gezme sayısını ifade ediyor (gezerken içindeki değerleri yazdırıyodu range olmadan)

0
1
2
3


In [ ]:
for i in range(0,len(a)):
  ab.append(a[i]*b[i])

In [ ]:
ab

[2, 6, 12, 20]

**DİPNOT:** Söz konusu makine öğrenmesi, veri bilimi olunca döngülere girmemek doğru olacaktır.

**FONKSİYONEL PROGRAMALAMA** ile yukarda oop örneğini yazalım

> NumPy, Python programlama dili için bir kütüphane olup, büyük, çok boyutlu diziler ve matrisler için destek eklerken, bu dizilerde çalışmak için yüksek düzeyli matematiksel fonksiyonların geniş bir koleksiyonudur.







In [ ]:
#vektörel bir operasyon görüldüğü gibi az çabayla yukarda uzun süren işlem "numpy" kütüphanesiyle  halledildi.
import numpy as np  
a=np.array([1,2,3,4]) #bu sefer burda numpy array i kullaranak a yı oluşturalım.
b=np.array([2,3,4,5]) #bu sefer burda numpy array i kullaranak b yi oluşturalım.



In [ ]:
a*b 

array([ 2,  6, 12, 20])

**MAP, FILTER, REDUCE**

In [ ]:
liste=[1,2,3,4,5]


In [ ]:
for i in liste:
  print(i+10)
#burda döngü ile her bir liste elemanına 10 ekleme yapıldı birde aşağıdaki örneği inceleyelim

11
12
13
14
15


**! ! ! MAP: Yapısı bize verilen bir nesne üzerinde bir fonksiyon tanımlama imkanı verir.**

In [ ]:
#burda nesne liste yapısı oluşturulan fonksiyon ise isimsiz fonksiyon olan lambda

list(map(lambda x:x+10,liste)) #görüldüğü üzere map ile de döngü kullanmadan aynı işlem gerçekleşmiş oldu.
#burda liste elemanları üzerinde 10 ekleme işlemi yapılmıştır.

[11, 12, 13, 14, 15]

**! ! ! FILTER:Bu yapı ile for ve if in yaptığı 2 ile tam bölünebilen sayıları bulma işlemini tek satırda halletmiş olur.**

In [ ]:
#filter
liste=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
list(filter(lambda x:x%2==0,liste))
#görüldüğü üzere ikiye tam bölünen değerler bulunup ekrana yazdırıldı.
#zaten fonksiyon yazılırken yukarda çıkan satırda hangi dğzende yazılması gerektiği gözükmektedir.


[2, 4, 6, 8, 10]

**! ! ! REDUCE:İndirgeme işlemi yapmaktadır.**

In [ ]:
from functools import reduce 
reduce(lambda a,b:a+b,liste)
#reduce() ile de liste içindeki elemanların toplamı tek satırda hallolmuş oldu.

55

# **MODÜL(KÜTÜPHANE,PAKET) OLUŞTURMAK VE İSTİSNALAR**

> **MODÜL:** Spesifik işlemleri kolaylaştırmak adına kullanılacak fonksiyonlar topluluğunun bir çatı altında toplanması denebilir.



In [ ]:
#görüldüğü gibi kendimiz .py uzantılı bir dosya oluşturup içerisine bir fonksiyon tanımladık. Ve bu artık bizim modülümüz oldu
#aşağıda kullanımı gösterilmekte.(yeni_maas modülde yer alan fonksiyonumuz)
import HesapModulu 
HesapModulu.yeni_maas(1000)

1200.0


In [ ]:
#daha kısa hali ile çağırma 
import HesapModulu as hm
hm.yeni_maas(2000)

2400.0


In [ ]:
#eğer ki ben yeni_maas() fonksiyonunu .yeni_maas() ile çağırmak istemezsem o zaman da şu şekilde kullanımı mevcut:
from HesapModulu import yeni_maas
yeni_maas(4000)

4800.0


In [ ]:
import deneme

In [ ]:
deneme.maaslar

[1000, 2000, 3000]

**İSTİSNALAR(EXCEPTIONS)/(HATALAR)**

In [ ]:
a=10
b=0
a/b

ZeroDivisionError: ignored

In [ ]:
try:
  print(a/b)
except ZeroDivisionError:
  print("paydada sıfır olmaz.")
#burda artık yukarda verilen hatanın adını yazarak bu hata alındığında bana bir çıktı ver. Programımı bozma ve yoksay.

paydada sıfır olmaz.


In [ ]:
#Type error
a=10
b='2'
a/b

TypeError: ignored

In [ ]:
try:
  a/b
except TypeError:
  print("bu hatayı görmezden gel")
  b=int(b)
  print(a/b)
#görüldüğü üzere burda b string olduğu için bölmedi ve bende bu hatayı aldığında b yi int e çevir ve öyle işlemi yap şeklinde bi exception verdim.

bu hatayı görmezden gel
5.0


# **SINAV SORULARI**

In [ ]:
def yap(x,y,z):
    try:
        print(x/y*z)
    except ZeroDivisionError:
        print("gecersiz islem")

yap(1,2,0)

0.0


In [ ]:
A = ["ali","veli","isik"]
B = [1,2,3]
AB = [A, B]

for i in AB:
    if type(i[0]) == str:
        print(list(map(lambda x: x + " hi", i))) 

['ali hi', 'veli hi', 'isik hi']


In [ ]:
AB

[['ali', 'veli', 'isik'], [1, 2, 3]]

In [ ]:
import numpy as np
a = np.array([1,1,1])
b = np.array([2])

a+b

array([3, 3, 3])

In [ ]:
fun = lambda x: x**2
fun(3)

9

In [ ]:
x="abcdef"
for i in x:
  print(i,end=" ")

#for yerine while olsaydı hata verirdi çünkü while da i tanımlaması gerekiyor.

a b c d e f 

# **PYTHON İLE VERİ MANİPÜLASYONU**



**NUMPY**

>  Numerical Python

> Bilimsel Hesaplamalar İçin Kullanılır


> Arraylar/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.

> Listelere benzerdir farkı ise verimli veri saklama ve vektörel operasyonlardır.(Yani listeler her bir eleman için type bilgisini ayrı ayrı tutmak isterken numpy bizi sabit type tutmaya zorlar ve hepsi için bir tane bilgi tutar bu da maaliyetten tasarruf)










**KISAYOLLAR:** kod  satırının dışına tıklayıp B ye basarsan hemen altına yeni bir kod satırı A ya basarsan da üstüne kod satırı eklenmiş olur

**NEDEN NUMPY ???**

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a
b#burda en son ne yazdıysak onu yazar ekrana 

array([2, 3, 4, 5])

In [ ]:
a*b

array([ 2,  6, 12, 20])

**NUMPY ARRAY İ OLUŞTURMAK**

> NumPy array i listeler gibi veri yapısıdır aslında.



In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [ ]:
np.array([3.14,2,12,6])
#burda çıktıda görüldüğü üzere sabit tip baskısı yüzünden hepsini float değere dönüştürdü.
#istersek tanımlama aşamasında int ve float olarak hepsi için bir tanımlama yapabiliriz.Aşağıdaki örnek gibi

array([ 3.14,  2.  , 12.  ,  6.  ])

In [ ]:
np.array([3.14,2,12,6], dtype="int")


array([ 3,  2, 12,  6])

**Sıfırdan Array Oluşturmak**

In [ ]:
np.zeros(10,dtype=int) #yazarkende görüldüğü üzere zeros float alır default bunu düzeltmek adına dtype kullanılır.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones([3,5],dtype=int) #burdada 3 e 5 lik ve 1 lerden oluşan matris oluşturduk.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((3,5),dtype=int) #köşeli parantezle de aynı sonucu veriyor.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#eğerki oluşturulan matris 1 ve 0 dışındakilerden oluşturulmak istenirse "np.full" kullanılır
np.full(5,3) #5 tane 3 den oluşsun

array([3, 3, 3, 3, 3])

In [ ]:
np.full((5,5),3) # 5x5 lik 3 lerden oluşsun

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
#iki sayı arasında doğrusal array oluşturma 
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
dir(np) #çıktısı uzun o yüzden çalıştırmıyorum ama burdan da numpy kütüphanesinin hangi fonksiyonları aldığını görebilirisn.

In [ ]:
np.linspace(0,1,10) #0 ile 1 arası 10 tane değer alsın.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.random.normal(10,4,(3,5)) #ortalaması 10 olan standart sapması 4 olan 3x5 lik matris içerisinde rastgele sayılar ata.

array([[11.63512517,  7.39279548,  9.8285402 , 14.68214093, 16.69328923],
       [11.06890514, 11.4533211 , 16.57669123,  4.62947777, 12.78413452],
       [ 9.36475002,  6.73479903, 15.63074786, 15.37801234, 13.37346117]])

In [ ]:
np.random.randint(0,10,(3,3)) #burda ise dağılımdan bağımsız olarak random sayılar üretilmiştir.

array([[9, 8, 4],
       [0, 0, 8],
       [8, 4, 6]])

**NUMPY ARRAY ÖZELLİKLERİ**

*   **ndim:** boyut sayısı 
*   **shape:** boyut bilgisi
*   **size:** toplam eleman sayısı
*   **dtype:** array veri tipi




In [ ]:
import numpy as np


In [ ]:
np.random.randint(10,size=10) #0 dan 10 10 tane rastgele değişkena atama

array([4, 9, 7, 1, 8, 2, 4, 2, 3, 9])

In [ ]:
a=np.random.randint(10,size=10)

In [ ]:
a.ndim

1

In [ ]:
a.shape #tek boyutlu ve 10 elemanlı

(10,)

In [ ]:
a.size

10

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.random.randint(10,size=(3,5))

In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 5)

In [ ]:
b.size

15

In [ ]:
b.dtype

dtype('int64')

**YENİDEN ŞEKİLLENDİRME(RESHAPING)**

In [ ]:
import numpy as np


In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.arange(1,10) #vektör

In [ ]:
a.ndim

1

In [ ]:
a.reshape((1,9)) #yukardakinden farklı olarak burda iki tane köşeli parantez var ve artık bu vektör değil matris formundadır.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
b=a.reshape((1,9)) #tek boyutun bilgisini bu şekilde matris formatına dönüştürmüş olduk.

In [ ]:
b.ndim #artık matris olduğu için de 2 boyutludur.

2

**ARRAY BİRLEŞTİRME(Concantenation)**

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

In [ ]:
np.concatenate([a,b,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#iki boyut için iki tane köşeli parantez
a=np.array([[1,2,3],
          [4,5,6]])

In [ ]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#sütun bazında birleştirme istersek axis default olarak 0 dır ve bu satırı temsil eder. 1 ise sütunu
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**ARRAY AYIRMA(SPLITTING)**

In [ ]:
import numpy as np


In [ ]:
x=np.array([1,2,3,9,99,78,5,1])

In [ ]:
t=np.split(x,[3,5])  #x i önce 3. ü index e kadar ayır 3 dahil değil sonra 5 e kadar ayır 3 ile 5 arası 5 dahil değil 
                   #diğer kısmı da olduğu gibi ekle bir şey belirtmek zorunda kalmadan 

In [ ]:
t

[array([1, 2, 3]), array([ 9, 99]), array([78,  5,  1])]

In [ ]:
t[1][0]

9

In [ ]:
?np.split() # bu şekilde split fonksiyonu hakkında yanda çıkan kutuda kullanımı ve açıklamasını görmek mümkün

In [ ]:
x,y,z=np.split(x,[3,5]) #bu şekilde her bir ayrılan array i bir değişkene atama işlemi yapmış olduk.

In [ ]:
x

array([1, 2, 3])

In [ ]:
y

array([ 9, 99])

In [ ]:
z

array([78,  5,  1])

In [ ]:
#İKİ BOYUTLU ARRAY AYIRMA
m=np.arange(16).reshape(4,4) #direk tek boyut üzerinden çok boyutlu array oluşturmak mümkün 
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vsplit(m,[2]) #2. index e kadar böl iki dahil değil sonrasını da aynen yaz

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
ust,alt=np.vsplit(m,[2])  #vertical split

In [ ]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
right,left=np.hsplit(m,2)

In [ ]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**SIRALAMA(SORTING)**

In [ ]:
import numpy as np


In [ ]:
v=np.array([65,26,12,3,45,79,95])
v

array([65, 26, 12,  3, 45, 79, 95])

In [ ]:
np.sort(v)

array([ 3, 12, 26, 45, 65, 79, 95])

In [ ]:
v #görüldüğü üzere orjinal üzerinde bir değişim gerçekleşmedi.

array([65, 26, 12,  3, 45, 79, 95])

In [ ]:
v.sort()  #burda ise ölümcül fonksiyon olarak işlenen bir uygulama vardır. görüldüğü üzere bu sefer array üzerinde kalıcı bir değişim gözlemlenmekte.
v

array([ 3, 12, 26, 45, 65, 79, 95])

In [ ]:
#İKİ BOYUTLU ARRAY SIRALAMA
h=np.random.normal(20,5,(3,3))
h

array([[16.23424678, 22.78313618, 25.03531038],
       [18.71466281, 16.64285904, 18.73505429],
       [27.7014566 , 10.74929116, 19.12849297]])

In [ ]:
np.sort(h,axis=1)  #satır bazında bir sıralama söz konusu

array([[16.23424678, 22.78313618, 25.03531038],
       [16.64285904, 18.71466281, 18.73505429],
       [10.74929116, 19.12849297, 27.7014566 ]])

In [ ]:
np.sort(h,axis=0) #burda ise sütun bazında bir sıralama söz konusu

array([[16.23424678, 10.74929116, 18.73505429],
       [18.71466281, 16.64285904, 19.12849297],
       [27.7014566 , 22.78313618, 25.03531038]])

**INDEX İLE ELEMANA ERİŞMEK**

In [ ]:
import numpy as np


In [ ]:
d=np.random.randint(10, size=10)
d

array([0, 2, 4, 7, 5, 5, 6, 6, 6, 8])

In [ ]:
d[0]

0

In [ ]:
d[-2] #tersten erişme

6

In [ ]:
d[0]=100 #eleman değiştirme
d

array([100,   2,   4,   7,   5,   5,   6,   6,   6,   8])

In [ ]:
k=np.random.randint(10, size=(3,5))
k

array([[1, 3, 8, 6, 0],
       [7, 0, 7, 9, 3],
       [1, 3, 5, 7, 6]])

In [ ]:
k[0,0]

1

In [ ]:
k[2,3]

7

In [ ]:
k[2,3]=10
k

array([[ 1,  3,  8,  6,  0],
       [ 7,  0,  7,  9,  3],
       [ 1,  3,  5, 10,  6]])

In [ ]:
k[0,0]=2.2  #burda np.array i tek bir sabit type kabul ettiği için float değer atasan bile array yapısı int olduğu için bunu da int e dönüştürüp ekleyecektir.
k

array([[ 2,  3,  8,  6,  0],
       [ 7,  0,  7,  9,  3],
       [ 1,  3,  5, 10,  6]])

**SLICING İLE ELEMANLARA ERİŞMEK(ARRAY ALT KÜMESİNE ERİŞMEK)**

> a[0:3] 0 dan 3 e kadar gitme slicing dir.



In [ ]:
import numpy as np


In [ ]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[0:3] #0 dan 3 e 3 dahil değil

array([20, 21, 22])

In [ ]:
a[:3]

array([20, 21, 22])

In [ ]:
a[3:]  #3 den sona kadar 

array([23, 24, 25, 26, 27, 28, 29])

In [ ]:
a[1::2] # 1 den sona kadar 2 şerli artarak gitme

array([21, 23, 25, 27, 29])

In [ ]:
a[2::3]

array([22, 25, 28])

**İki Boyutlu Slicing İşlemi**

In [ ]:
m=np.random.randint(10,size=(5,5))
m

array([[4, 5, 9, 3, 3],
       [4, 6, 5, 9, 9],
       [4, 1, 7, 1, 1],
       [9, 7, 8, 1, 2],
       [3, 7, 2, 6, 1]])

In [ ]:
m[:,0] # ":" burda bütün satırı seç demek aslında 0 ise 0. sütunu al

array([4, 4, 4, 9, 3])

In [ ]:
m[:,1][2]  #burda ise bütün satırı seç 1. sütunu al ve ordaki 2. elemana eriş

1

In [ ]:
m[0,:] #ilk satırda bütün sütunları getir.

array([4, 5, 9, 3, 3])

In [ ]:
m[0] #yazınca da saten ilk satırı getirecektir.

array([4, 5, 9, 3, 3])

In [ ]:
m[1,:]

array([4, 6, 5, 9, 9])

In [ ]:
m[0:2,0:3] #burda ise 0 dan 2 ye (2 dahil değil) satırları al 0 dan 3 e sütunları al. Sonuç olarak 2 tane satır 3 tane sütundan oluşan bir çıktı oluşacak

array([[4, 5, 9],
       [4, 6, 5]])

In [ ]:
m[:,2] #bütün satırları al ve 1. sütunu getir

array([9, 5, 7, 8, 2])

In [ ]:
m[:,:2] #bütün satırları al ve 0 dan 2 ye bütun sütunları al  == m[:,0:2]

array([[4, 5],
       [4, 6],
       [4, 1],
       [9, 7],
       [3, 7]])

In [ ]:
m

array([[4, 5, 9, 3, 3],
       [4, 6, 5, 9, 9],
       [4, 1, 7, 1, 1],
       [9, 7, 8, 1, 2],
       [3, 7, 2, 6, 1]])

In [ ]:
m[1:3,0:2] #spesifik bir bölge seçtik aslında

array([[4, 6],
       [4, 1]])

**ALT KÜME ÜZERİNDE İŞLEM YAPMAK**

In [ ]:
import numpy as np


In [ ]:
a=np.random.randint(10,size=(5,5))
a

array([[8, 1, 5, 7, 4],
       [7, 3, 1, 2, 2],
       [2, 3, 2, 4, 8],
       [1, 9, 3, 7, 5],
       [0, 1, 0, 8, 6]])

In [ ]:
alt_a=a[0:3,0:2]
alt_a

array([[8, 1],
       [7, 3],
       [2, 3]])

**DİKKAT!!!**

In [ ]:
alt_a[0,0]=4544   #burda yapılan işlem sonucu alt işlem olmasına rağmen görüldüğü üzere ana array i de değiştirmektedir.
alt_a[1,1]=777

In [ ]:
a

array([[4544,    1,    5,    7,    4],
       [   7,  777,    1,    2,    2],
       [   2,    3,    2,    4,    8],
       [   1,    9,    3,    7,    5],
       [   0,    1,    0,    8,    6]])

In [ ]:
#yukardaki değişimin önüne geçmek için copy fonksiyonunu kullanabiliriz.

In [ ]:
b=np.random.randint(10,size=(5,5))
b

array([[6, 3, 5, 2, 7],
       [7, 1, 2, 3, 0],
       [5, 4, 3, 8, 1],
       [6, 9, 6, 6, 1],
       [1, 2, 5, 8, 9]])

In [ ]:
alt_b=b[0:3,0:2].copy()
alt_b

array([[6, 3],
       [7, 1],
       [5, 4]])

In [ ]:
alt_b[0,0]=3333
alt_b

array([[3333,    3],
       [   7,    1],
       [   5,    4]])

In [ ]:
b #görüldüğü üzere alt küme de copy() fonksiyonu kullanıldığında ana array de değişimin önüne geçilmiştir.

array([[6, 3, 5, 2, 7],
       [7, 1, 2, 3, 0],
       [5, 4, 3, 8, 1],
       [6, 9, 6, 6, 1],
       [1, 2, 5, 8, 9]])

**! ! ! FANCY INDEX İLE ELEMANLARA ERİŞMEK**

In [ ]:
import numpy as np


In [ ]:
p=np.arange(0,30,3)
p

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
p[1]

3

In [ ]:
#eğer ki istediğimiz indexlerin hepsine bir anda erişmek istersek [] içine alarak elde edebiliriz.
[p[1],p[3],p[5]] 

[3, 9, 15]

**Fancy index->>**

> Aslında array in erişilmek istenen elemanı için içine liste şeklinde ifade yerleştirmek







In [ ]:
#görüldüğü gibi bu işlemle de yukarda yapılanı sağlamış oldu ve buna fancy indexleme deniyor.
al_getir=[1,2,3] #array içinden çekilmek istenen indexleri liste formatında kaydedersek ve p[al_getir] dersek bunnları algılar ve o indexleri getirir.

In [ ]:
p

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
p[al_getir] 

array([3, 6, 9])

In [ ]:
#iki boyutta fancy
l=np.arange(9).reshape((3,3))
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
satir=np.array([0,1])
sütun=np.array([1,2])

In [ ]:
l[satir,sütun] #bu şekilde içine yukarda array olarak tanımlanan değişkenleri yazarsak bize sonucu verdiğini görürüz.

array([1, 5])

In [ ]:
l[[0,1],[1,2]] #yukardakinin içine direk istenilenlerin yazılmış hali de bu şekildedir. iki örnek de fancy index olarak kabul edilir. 

array([1, 5])

**Basit Index İle Fancy Index**

In [ ]:
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
l[1,2]

5

In [ ]:
l[1,[0,1,2]] #1. satırı al sütunda ise direk içinde yazılanları getir.

array([3, 4, 5])

In [ ]:
l[0,[1,2]]  #burda artık e kadar yok 0. satırı al sütunda ise 1 ve 2. sütunu al demek istiyor.

array([1, 2])

**Slice İle Fancy**

In [ ]:
l[0:,[1,2]] #burda da 0 dan başla bütün satırları al ve sütun olarak da 1 ve 2 yi getir

array([[1, 2],
       [4, 5],
       [7, 8]])

**KOŞULLU ELEMAN İŞLEMLERİ**

In [ ]:
import numpy as np


In [ ]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [ ]:
v<3

array([ True,  True, False, False, False])

In [ ]:
#peki burda hangi indexler doğru hangileri yanlış anlamak istersek tekrar fancy yapısını ele almaktayız.
v[v<3]

array([1, 2])

In [ ]:
v[v>3]

array([4, 5])

In [ ]:
v[v<=3]

array([1, 2, 3])

In [ ]:
v[v!=3]

array([1, 2, 4, 5])

In [ ]:
v

array([1, 2, 3, 4, 5])

In [ ]:
v*3

array([ 3,  6,  9, 12, 15])

In [ ]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
v**2

array([ 1,  4,  9, 16, 25])

# **MATEMATİKSEL İŞLEMLER**

In [ ]:
import numpy as np

In [ ]:
v=np.array([1,2,3,4,5])

In [ ]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [ ]:
v-1

array([0, 1, 2, 3, 4])

**ufunc**

In [ ]:
np.subtract(v, 1)
#bir üst satır ile aynı işlevi görmekte aslında biz v-1 dediğimizde numpy daki substract fonksiyonunu çalıştırmış olmaktayız.

array([0, 1, 2, 3, 4])

In [ ]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [ ]:
np.power(v,3)
#v**3 ile aynı anlamda aslında

array([  1,   8,  27,  64, 125])

In [ ]:
#v%2 demek 2 ye bölümünden kalanları getir demektir ve aşağıdaki np fonksiyonu bu işlemi gerçekleştirir.
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [ ]:
np.absolute(np.array([-3]))

array([3])

In [ ]:
np.sin(360)

0.9589157234143065

In [ ]:
np.cos(180)

-0.5984600690578581

In [ ]:
v=np.array([1,2,3])

In [ ]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [ ]:
np.log10(v) 
#burda ise log yanına sayılarla derecesini belirtmek mümkün.

array([0.        , 0.30103   , 0.47712125])

In [ ]:
?np #ile yanda yardım kutusu altında bilgiler mavcut numpy a dair.

In [ ]:
#EKSTRA
np.linspace(0,2,9) #o dan başla 2 de dahil 2 ye kadar 9 tane sayı üret demek 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**CHEAT SHEETS IS VERY IMPORTANT FOR BASIC PYTHON LIBRARY ATTIRIBUTE**

In [ ]:
np.sum(v)

6

In [ ]:
v.sum()

6

In [ ]:
np.mean(v)

2.0

In [ ]:
v.mean()

2.0

**NUMPY İLE İKİ BİLİNMEYENLİ DENKLEM ÇÖZÜMÜ**

In [ ]:
import numpy as np


In [ ]:
#5*x0 + x1=12       
#x0 + 3*x1=10

#yukarıdaki iki bilinmeyen denklemi çözmek için öncelikle bunu bilgisayarın anlayacağı bir dile çevirmek lazım.

a=np.array([[5,1],[1,3]]) #bir liste içinde iki denklemin kat sayılarını yazarız
b=np.array([12,10]) #burda ise eşitliğin sağ tarafını kullanarak bir array daha oluştururuz.

In [ ]:
np.linalg.solve(a,b)  #np altında oluşturulan paketlerden linalg in solve foksiyonu yardımı ile bu denklem dizini çözülmüş olur.

array([1.85714286, 2.71428571])

**SINAV SORULARI**

In [ ]:
import numpy as np

np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [ ]:

import numpy as np
np.random.randint(10, size = (3,3,2))

array([[[7, 2],
        [9, 0],
        [2, 1]],

       [[5, 6],
        [1, 9],
        [5, 8]],

       [[7, 9],
        [4, 2],
        [3, 8]]])

In [ ]:
a=np.random.randint(10,size=(3,5))
a

array([[8, 1, 9, 4, 5],
       [3, 9, 4, 9, 7],
       [9, 1, 4, 6, 9]])

In [ ]:
a[0:1]

array([[8, 1, 9, 4, 5]])

**PANDAS**


> Panel Data(Zaman indexi ön planlı)

> Yapısal veri setleriyle daha geniş çalışma alanı

> Veri Manipülasyonu ve veri analizi için yazılmış açık kaynak kodlu python kütüphanesi

> Ekonomik ve finansal çalışmalar için doğmuştur.

> R DataFrame yapısını pythona taşımış ve DataFrameler üzerinde hızlı ve etkili çalışma imkanı sağlamış

> Bİrçok farklı veri tipini okuma ve yazma




**Pandas Serileri(pandas veri tipi,tek boyutlu) Oluşturmak**


> numpy array in den farklı olarak index bilgisi de tutar (numpy sadece veri tipi tutuyordu.)



In [ ]:
import pandas as pd


In [ ]:
pd.Series([1,2,3,4,5])
#aşağıda verilen ilk sütun index leri diğer sütun ise içinde oluşturulan listeyi ifade eder.

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
seri=pd.Series([1,2,3,4,5])
type(seri)

pandas.core.series.Series

In [ ]:
seri.axes
#burda içinde barındırdıkları bilgisi veriliyot 0 dan 5 e kadar 1 er 1 er artmış index i

[RangeIndex(start=0, stop=5, step=1)]

In [ ]:
seri.size

5

In [ ]:
seri.ndim

1

In [ ]:
seri.dtype

dtype('int64')

In [ ]:
seri.values
#burda ise indexleri görmek istemiyorsak (numpy array gibi) ".values" yardımı ile erişmek mümkün

array([1, 2, 3, 4, 5])

In [ ]:
seri.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
seri.head(3)
#burda ise ilk 3 elemanı getir diyoruz

0    1
1    2
2    3
dtype: int64

In [ ]:
seri.tail(3)
#bu ise son 3 elemanı bize gösterir.

2    3
3    4
4    5
dtype: int64

**index isimlendirme**

> bunu  aynı dictionary yapısı gibi düşünebiliriz.



In [ ]:
seri=pd.Series([55,36,12,36,23,45])
seri

0    55
1    36
2    12
3    36
4    23
5    45
dtype: int64

In [ ]:
seri=pd.Series([55,36,12,36,23,45],index=[1,3,5,7,9,4])  #index e default ataması yerine kendimiz değerler verdik
seri

1    55
3    36
5    12
7    36
9    23
4    45
dtype: int64

In [ ]:
seri=pd.Series([55,36,12,36,23,45],index=["j","b","g","p","k","h"])  #index e default ataması yerine kendimiz değerler verdik ve bunları string olarak da yazabilmek mümkün
seri

j    55
b    36
g    12
p    36
k    23
h    45
dtype: int64

In [ ]:
#aynı dictionary yapısındaki gibi key i ni yazdık value sunu verdi gib burda da isimlendirdiğimiz index i yazdık bize değerini verdi.
seri["j"] 

55

In [ ]:
seri["j":"p"] #burda da slicing işlemi yapılabiliyor burda ekstra son yazdığında alınıyor.

j    55
b    36
g    12
p    36
dtype: int64

**DICTIONARY üzerinden series oluşturma**

In [ ]:

sozluk={"reg":10,"log":20,"cart":30}
seri=pd.Series(sozluk)
seri

reg     10
log     20
cart    30
dtype: int64

In [ ]:
#aynı işlemi bu sefer farklı şekilde yazalım
sozluk=pd.Series({"reg":10,"log":20,"cart":30})
sozluk

reg     10
log     20
cart    30
dtype: int64

In [ ]:
sozluk["reg"]

10

In [ ]:
sozluk["reg":"log"]  #yine burda da slicing işlemi yapmak mümkün

reg    10
log    20
dtype: int64

**İki seriyi birleştirerek  seri oluşturma**

In [ ]:
pd.concat([sozluk,sozluk]) #liste gibi [] içine yazarak çağrılır dataframe üzerinde işlem yaptığı için 

reg     10
log     20
cart    30
reg     10
log     20
cart    30
dtype: int64

**Eleman İşlemleri**

In [ ]:
import numpy as np
import pandas as pd

a=np.array([1,2,3,65,45])
seri=pd.Series(a)
seri
#burda görüldüğü üzere numpy array i kullanılarak da pandas serisi oluşturmak mümkün 

0     1
1     2
2     3
3    65
4    45
dtype: int64

In [ ]:
seri[2]

3

In [ ]:
seri[2:4] #2 dahil 4 e kadar olanı al slicing

2     3
3    65
dtype: int64

In [ ]:
seri=pd.Series([1,23,45,62],index=["reg","log","cart","rf"])
seri

reg      1
log     23
cart    45
rf      62
dtype: int64

In [ ]:
seri.keys

<bound method Series.keys of reg      1
log     23
cart    45
rf      62
dtype: int64>

In [ ]:
seri.index

Index(['reg', 'log', 'cart', 'rf'], dtype='object')

In [ ]:
list(seri.items()) #burda aynı dictionary yapısında olduğu gibi key value çiftlerini bir arada getirir.list deidğimiz için bunları liste içinde ayırarak yazdırmış olduk


[('reg', 1), ('log', 23), ('cart', 45), ('rf', 62)]

In [ ]:
seri.values

array([ 1, 23, 45, 62])

**Eleman Sorgulama**

In [ ]:
#istediğim sey serinin içinde mi bunu sorgulamak istiyorum 
"reg" in seri

True

In [ ]:
"a" in seri

False

In [ ]:
seri["reg"]

1

**fancy eleman**

In [ ]:
seri[["reg","log"]] #fancy ile istenilen iki eleman yine [] içlerinde yazılarak ekrana yazdırılabilir.

reg     1
log    23
dtype: int64

In [ ]:
seri["reg"]=160
seri
#burda da yeniden atama yapabilmekteyiz.

reg     160
log      23
cart     45
rf       62
dtype: int64

In [ ]:
seri["reg":"cart"] #slicing

reg     160
log      23
cart     45
dtype: int64

**PANDAS DATAFRAME OLUŞTURMA**

> Makine öğrenmesine verilecek olan datasetler olarak düşünebiliriz



In [ ]:
import pandas as pd


In [ ]:
liste=pd.Series([12,32,56,12,45])
liste

0    12
1    32
2    56
3    12
4    45
dtype: int64

In [ ]:
pd.DataFrame(liste,columns=["degisken_adi"])

degisken_adi
0            12
1            32
2            56
3            12
4            45

In [ ]:
import numpy as np
liste2=np.arange(9).reshape((3,3))  #arange(1,10) ile aynı aslında 0 dan başlatılıyor sadece 
liste2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
liste4=np.arange(0,8,2).reshape((2,2))   #deneme dataframe den bağımsız
liste4

array([[0, 2],
       [4, 6]])

In [ ]:
liste3=np.random.randint(1,10,size=(3,6))    #deneme dataframe den bağımsız
liste3

array([[2, 7, 3, 7, 7, 4],
       [5, 4, 9, 8, 3, 2],
       [9, 8, 7, 5, 4, 9]])

In [ ]:
liste2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#burda da görüldüğü üzere DataFrame olarak oluşturduğumuz numpy çok boyutlu matrisini parametre olarak vermiş olduk. columns ile de sütun isimlendirmeleri yapıldı
pd.DataFrame(liste2,columns=["var1","var2","var3"])

var1  var2  var3
0     0     1     2
1     3     4     5
2     6     7     8

In [ ]:
#DATAFRAME isimlendirme

df=pd.DataFrame(liste2,columns=["var1","var2","var3"])
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df.columns=("deg1","deg2","deg3")  
df


deg1  deg2  deg3
0     0     1     2
1     3     4     5
2     6     7     8

In [ ]:
df.columns[0]

'deg1'

In [ ]:
df.columns[0]=("hello") #bunu kabul etmiyor hata verecektir tek tek index alarak değiştirilmez

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.axes #axes bize satır ve sütun bilgilerini veriyor.

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [ ]:
df.shape #3x3 lük matris

(3, 3)

In [ ]:
df.ndim #2 boyutlu 

2

In [ ]:
df.size #kaç tane veri mevcut

9

In [ ]:
df.values #sadece value değerlerini getirir.
#görüldüğü gibi bize bunu numpy array ine çevirdi

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
type(df.values)

numpy.ndarray

In [ ]:
df

deg1  deg2  deg3
0     0     1     2
1     3     4     5
2     6     7     8

In [ ]:
df.deg1 #direk sütunun adıyla da çağırmak mümkün

0    0
1    3
2    6
Name: deg1, dtype: int64

In [ ]:
df.head() #bize ilk değerleri getirir.

deg1  deg2  deg3
0     0     1     2
1     3     4     5
2     6     7     8

In [ ]:
df.head(2) #ilk ikiyi getir dedik

deg1  deg2  deg3
0     0     1     2
1     3     4     5

In [ ]:
df.tail() #sondan değeleri getirir.

deg1  deg2  deg3
0     0     1     2
1     3     4     5
2     6     7     8

In [ ]:
df.tail(2) #son iki değeri bize vermiş olur 

deg1  deg2  deg3
1     3     4     5
2     6     7     8

**ELEMAN İŞLEMLERİ**

In [ ]:
import numpy as np

In [ ]:
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)

In [ ]:
sozluk={"var1":s1,"var2":s2,"var3":s3}   #burda dictionary içinde numpy array i kullanıldı.
sozluk

{'var1': array([9, 0, 6, 2, 9]),
 'var2': array([1, 7, 8, 8, 9]),
 'var3': array([7, 1, 1, 6, 9])}

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(sozluk)   #dictioınary kullanılarak dataframe oluşturmak mümkün 
df

var1  var2  var3
0     9     1     7
1     0     7     1
2     6     8     1
3     2     8     6
4     9     9     9

In [ ]:
df[0:2]  #0 dan 2 ye 2 dahil değil indexleri getir. Slicing 

var1  var2  var3
0     9     1     7
1     0     7     1

In [ ]:
df.index=["a","b","c","d","e"] #burda index değerlerinin isimlerini değiştirebiliriz.

In [ ]:
df

var1  var2  var3
a     9     1     7
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
df[0:2]

var1  var2  var3
a     9     1     7
b     0     7     1

In [ ]:
df["c":"e"]  #c den e ye 

var1  var2  var3
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
#SİLME
df.drop("a",axis=0)  #axis i verme sebebimiz o satırı silme olduğunu ifade etmek

var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
df #ancak yukardaki silme kalıcı olmadı.

var1  var2  var3
a     9     1     7
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
df.drop("a",axis=0,inplace=True)  #inplace sayesinde kalıcı silme işlemi yapabildik True diyerek / default false döndürüyor
df

In [ ]:
df

var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
#fancy ile birden fazla satır silmek mümkün.

l=["c","e"]

In [ ]:
df.drop(l,axis=0) #inplace olmadığı için tabiki kalıcı silme olmadı.

var1  var2  var3
b     0     7     1
d     2     8     6

In [ ]:
df.drop(["c","e"],axis=0)   #direk içine bu şekilde yazmak da mümkün

var1  var2  var3
b     0     7     1
d     2     8     6

In [ ]:
#değişkenler için 
df

var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
"var1" in df

True

In [ ]:
l=["var1","var4","var2"]

In [ ]:
for i in l:     #burda for sayesinde l içinde gezinerek o değişkenler df dataframe inde var mı yok mu test ettik.
  print(i in df)

True
False
True


In [ ]:
df

var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
#yeni bir değişken oluşturulacak(sütun bazında) ve bu var1 ve var2 nin çarpımı sonucu olsun istiyoruz.
var4=df.var1*df.var2
var4

b     0
c    48
d    16
e    81
dtype: int64

In [ ]:
df["var4"]=var4   #burda [] içine yazdığımızda olmasa bile olmadığını anlayıp bu ismi ekliyo 

In [ ]:
df

var1  var2  var3  var4
b     0     7     1     0
c     6     8     1    48
d     2     8     6    16
e     9     9     9    81

In [ ]:
df.var1

b    0
c    6
d    2
e    9
Name: var1, dtype: int64

In [ ]:
df["var1"]

b    0
c    6
d    2
e    9
Name: var1, dtype: int64

In [ ]:
#değişken silmek 
df.drop("var4",axis=1)


var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
df #görüldüğü üzere üst satırdaki değişim kalıcı olmadı o yüzden inplace kullanalım

var1  var2  var3  var4
b     0     7     1     0
c     6     8     1    48
d     2     8     6    16
e     9     9     9    81

In [ ]:
df.drop("var4",axis=1,inplace=True)

In [ ]:
df 

var1  var2  var3
b     0     7     1
c     6     8     1
d     2     8     6
e     9     9     9

In [ ]:
#fancy ile sütun silme
df.drop(["var1","var2"], axis=1)

var3
b     1
c     1
d     6
e     9

**GÖZLEM VE DEĞİŞKEN SEÇİMİ ->>loc,iloc**

In [ ]:
?np.random.randint

In [ ]:
import numpy as np
import pandas as pd
m=np.random.randint(1,30,size=(10,3))
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0     5    24     5
1     5    10    10
2    17     1    25
3    18     7     5
4    28    24    11
5    19     5    24
6    24    17    18
7    16    23    13
8    10     3     3
9    10     3    25

**loc->>**tanımlandığı şekli ile seçim yapmak için kullanılır.

In [ ]:
?df.loc #? işareti ile kullanımını görmek mümkün 

In [ ]:
df.loc[0:3]  #görüldüğü üzere olduğu gibi getirdi 0 dan 3 dahil olmak üzere

var1  var2  var3
0     5    24     5
1     5    10    10
2    17     1    25
3    18     7     5

**iloc->>**alışık olduğumuz indexleme mantığı ile seçim yapar.

In [ ]:
?df.iloc

In [ ]:
df.iloc[0:3]  #burda ise alışık olduğumuz slicing işlemi mevcut

var1  var2  var3
0     5    24     5
1     5    10    10
2    17     1    25

In [ ]:
df.iloc[:3,:2]

var1  var2
0     5    24
1     5    10
2    17     1

In [ ]:
df.loc[:3,"var3"]

0     5
1    10
2    25
3     5
Name: var3, dtype: int64

In [ ]:
df.iloc[:3,"var3"]
#bu hata verir çünkü iloc da loc gibi direk değşken ismini veremiyoruz.


In [ ]:
df.iloc[:3]["var3"] #yukardaki işlemi bu şekilde bir yazım ile yapmak mümkün

0     5
1    10
2    25
Name: var3, dtype: int64

In [ ]:
df[0:2] #bu da klasik indexleme işlemi

var1  var2  var3
0     5    24     5
1     5    10    10

**Koşullu Eleman İşlemleri**

In [ ]:
df

var1  var2  var3
0     5    24     5
1     5    10    10
2    17     1    25
3    18     7     5
4    28    24    11
5    19     5    24
6    24    17    18
7    16    23    13
8    10     3     3
9    10     3    25

In [ ]:
df["var1"]

0     5
1     5
2    17
3    18
4    28
5    19
6    24
7    16
8    10
9    10
Name: var1, dtype: int64

In [ ]:
df.var1

0     5
1     5
2    17
3    18
4    28
5    19
6    24
7    16
8    10
9    10
Name: var1, dtype: int64

In [ ]:
df.var1="var12" #içeriğini tamamen değiştiriyor değişken ismini değil df["var1"]="var12" ile de aynı sonuç verilir.

In [ ]:
df


var1  var2  var3
0  var12    24     5
1  var12    10    10
2  var12     1    25
3  var12     7     5
4  var12    24    11
5  var12     5    24
6  var12    17    18
7  var12    23    13
8  var12     3     3
9  var12     3    25

In [ ]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0     5    24     5
1     5    10    10
2    17     1    25
3    18     7     5
4    28    24    11
5    19     5    24
6    24    17    18
7    16    23    13
8    10     3     3
9    10     3    25

In [ ]:
df.columns


Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df.columns[0]

'var1'

In [ ]:
df[0:3]["var2"]

0    24
1    10
2     1
Name: var2, dtype: int64

**eğer birden fazla değişken ismini çağırmak istersek burda fancy kullanmayı unutma**

In [ ]:
df[0:3][["var1","var2"]]

var1  var2
0     5    24
1     5    10
2    17     1

In [ ]:
df.var1>6

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: var1, dtype: bool

In [ ]:
df["var1"]>6

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: var1, dtype: bool

 **peki bize 6 dan büyükleri getirsin istersek**


In [ ]:
df[df.var1>6]   #burda değişkenlerin hepsini getirdi peki spesifik bir değişken(sütun) istersek 

var1  var2  var3
2    17     1    25
3    18     7     5
4    28    24    11
5    19     5    24
6    24    17    18
7    16    23    13
8    10     3     3
9    10     3    25

In [ ]:
df[df.var1>6]["var2"]  #var1 in 6 dan büyük olan elemanlarının olduğu satırlarda var2 değişkeninin değerlerini bize getir

2     1
3     7
4    24
5     5
6    17
7    23
8     3
9     3
Name: var2, dtype: int64

In [ ]:
df[(df.var1 >6)&(df.var3<5)]

var1  var2  var3
8    10     3     3

In [ ]:
?df.loc #direk bizim yazdığımızı alıyor.

In [ ]:
df.loc[(df.var1 >6),["var1","var2"]] #loc olamdığında hata verecektir. ancak log yazığımızı algıladığı içine isteneni getirir. peki loc olmadan nasıl yazarız?


var1  var2
2    17     1
3    18     7
4    28    24
5    19     5
6    24    17
7    16    23
8    10     3
9    10     3

In [ ]:
#tabiki fancy kullanarak  [[]] içine yazarak iki tane köşeli parantez olmalı
df[df.var1>6][["var1","var2"]]

var1  var2
2    17     1
3    18     7
4    28    24
5    19     5
6    24    17
7    16    23
8    10     3
9    10     3

**Birleştirme (Join) İşlemleri**

In [ ]:
import numpy as np
import pandas as pd
m=np.random.randint(1,30,size=(5,3))
df1=pd.DataFrame(m,columns=["var1","var2","var3"])
df1

var1  var2  var3
0    28     1     9
1    18     8    17
2    24    24    29
3     1    10    22
4     4    23    24

In [ ]:
df2=df1+65 #df1 in üzerine sayı ekleme ile oluşturulan bir diğer dataframe oluşturma

In [ ]:
df2

var1  var2  var3
0    93    66    74
1    83    73    82
2    89    89    94
3    66    75    87
4    69    88    89

In [ ]:
pd.concat([df1,df2]) #içine axis=1 eklendiğinde sütun bazında ekleme yapmış olacak
#burda görüldüğü üzere indexleme tekrar sıfırdan başlamakta birleştirme olduğunda.

var1  var2  var3
0    28     1     9
1    18     8    17
2    24    24    29
3     1    10    22
4     4    23    24
0    93    66    74
1    83    73    82
2    89    89    94
3    66    75    87
4    69    88    89

In [ ]:
#peki bu sorunu nasıl çözebiliriz? ?pd.concat yazdığında aldığı parametrelere bakıldığında görülecek ki ignore_index adında ve false döndüren bir parametre mevcut
pd.concat([df1,df2],ignore_index=True) 
#görüldüğü gibi indexi görmezden gelerek yukarda oluşan sorun çözülmüş oldu.


var1  var2  var3
0    28     1     9
1    18     8    17
2    24    24    29
3     1    10    22
4     4    23    24
5    93    66    74
6    83    73    82
7    89    89    94
8    66    75    87
9    69    88    89

In [ ]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df2.columns 

Index(['var1', 'var2', 'var3'], dtype='object')

In [ ]:
df2.columns=["var1","var2","deg3"]
df2

var1  var2  deg3
0    93    66    74
1    83    73    82
2    89    89    94
3    66    75    87
4    69    88    89

In [ ]:
df1

var1  var2  var3
0    28     1     9
1    18     8    17
2    24    24    29
3     1    10    22
4     4    23    24

In [ ]:
pd.concat([df1,df2],ignore_index=True)  #burda Nan verme sebebi hata vermesi aslında deg3 iki dataframe de de olmadığı için 

var1  var2  var3  deg3
0    28     1   9.0   NaN
1    18     8  17.0   NaN
2    24    24  29.0   NaN
3     1    10  22.0   NaN
4     4    23  24.0   NaN
5    93    66   NaN  74.0
6    83    73   NaN  82.0
7    89    89   NaN  94.0
8    66    75   NaN  87.0
9    69    88   NaN  89.0

In [ ]:
pd.concat([df1,df2],join="inner") #yukardaki soruna çözüm olarak zaten değişken isimleri aynı olmayan dataframeleri birleştirmek doğru olmayacağından
                                  #join="inner" kullanarak kesişimlerinin birleştirilmesine olanak sağladık.

var1  var2
0    28     1
1    18     8
2    24    24
3     1    10
4     4    23
0    93    66
1    83    73
2    89    89
3    66    75
4    69    88

In [ ]:
pd.concat([df1,df2],join_axes=[df1.columns],ignore_index=True) 
#bu artık kullnım dışı

TypeError: ignored

In [ ]:
pd.concat([df1,df2],ignore_index=True)


var1  var2  var3  deg3
0    28     1   9.0   NaN
1    18     8  17.0   NaN
2    24    24  29.0   NaN
3     1    10  22.0   NaN
4     4    23  24.0   NaN
5    93    66   NaN  74.0
6    83    73   NaN  82.0
7    89    89   NaN  94.0
8    66    75   NaN  87.0
9    69    88   NaN  89.0

In [ ]:
pd.__version__

'1.1.5'

In [ ]:
!python --version

Python 3.6.9


In [ ]:
df

var1  var2  var3
0    20    20    16
1     7    18    21
2    13     7    10
3    24    15    17
4     7    27     3

In [ ]:
df.rename_axis("var45", axis=1) #bununla indexlere isimlendirme yapabilirsin

var45  var1  var2  var3
0        20    20    16
1         7    18    21
2        13     7    10
3        24    15    17
4         7    27     3

**İLERİ BİRLEŞTİRME İŞLEMLERİ**

In [ ]:
import pandas as pd


**dictionary hatırlatma**

In [ ]:
dff={"calisanlar":["Ali","Veli","Ayse","Fatma"],               #dictionary kullanma
                  "grup":["Muhasebe","Muhendislik","Muhendislik","Ik"]}
dff

{'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
 'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'Ik']}

In [ ]:
dff.keys()

dict_keys(['calisanlar', 'grup'])

In [ ]:
dff.values()

dict_values([['Ali', 'Veli', 'Ayse', 'Fatma'], ['Muhasebe', 'Muhendislik', 'Muhendislik', 'Ik']])

In [ ]:
dff["calisanlar"][2]

'Ayse'

**konuya giriş**

In [ ]:
df1=pd.DataFrame({"calisanlar":["Ali","Veli","Ayse","Fatma"],               #dictionary kullanarak dataframe oluşturma
                  "grup":["Muhasebe","Muhendislik","Muhendislik","Ik"]})
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           Ik

In [ ]:
df2=pd.DataFrame({"calisanlar":["Ayse","Ali","Veli","Fatma"],
                  "ilk_giris":[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [ ]:
pd.merge(df1,df2)   #iki veri setinde de calisanlar olduğu için ona göre birleşim yaptı

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           Ik       2019

In [ ]:
pd.merge(df1,df2,on="calisanlar")  #on ile de hangisine göre birleştirmek istediğini spesifik olarak belirtmek mümkün

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           Ik       2019

**many to one**

In [ ]:
df3=pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           Ik       2019

In [ ]:
df4=pd.DataFrame({"grup":["Muhasebe","Muhendislik","Ik"],
                  "mudur":["Caner","Mustafa","Berkcan"]})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           Ik  Berkcan

In [ ]:
pd.merge(df3,df4)  #burda ise df3 de gruplar 4 tane idi ancak df4 de grup 3 tane. bunların aynı olanlarını eşleyerek birleştirme yapıyor.

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           Ik       2019  Berkcan

**one to many**

In [ ]:
df5=pd.DataFrame({"grup":["Muhasebe","Muhasebe","Muhendislik","Muhendislik","Ik","Ik"],
                  "yetenekler":["matematik","excel","kodlama","linux","excel","yonetim"]})
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           Ik      excel
5           Ik    yonetim

In [ ]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           Ik

In [ ]:
pd.merge(df1,df5)   #burda ise df1 de çalışanlar tekti ama birleştirince çoklama meydana geldi.

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           Ik      excel
7      Fatma           Ik    yonetim